### PR TITLE
Change to StockLevel class for UpdateStock Command

### LINKED ISSUE #143: (Feature bug) Large numbers causes "non-negative integer" warning in update_stock
For update_stock, a stock level of a very large number will cause the console to output the "non-negative integer" error.
image

### PR DESCRIPTION
**Pull request by Anvita2110**
### Changes made in this PR:
- Updated from int to StockLevel for Update Stock Command
- Changed few error messages for validility
- Updated unit tests accordingly
- Tested and fixed most of the errors : Closes Alpha Test Bug 143

Closes #143

### CODE REVIEW

**Review by zacharyxzz — COMMENTED** [review]
LGTM, though I do not entirely understand the change from int to a StockLevel class.

**Comment by Anvita2110** [comment]
@T1duS Can you please make UpdateStockLevelCommandTest so that code coverage issue is cleared.

**Review by ritulkrsingh — CHANGES_REQUESTED** [review]
Could you remove `UpdateMaxStockLevelCommand` as that does a subset of what `SetThresholdCommand` does. Also the current implementation (of the former) is broken.

**Review by ritulkrsingh — APPROVED** [review]
Looks good, can merge!

**Pull request merged**
